repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^helm/
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: phpstan
        name: PHPStan
        entry: ./vendor/bin/phpstan analyse --memory-limit=2G
        language: system
        types: [php]
        pass_filenames: false

      - id: pint
        name: Laravel Pint
        entry: ./vendor/bin/pint
        language: system
        types: [php]
        pass_filenames: false
