replicaCount: 3

image:
  repository: your-registry/laravel-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: laravel-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
