name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: laravel-app
  EKS_CLUSTER_NAME: my-cluster
  HELM_CHART_PATH: ./helm/laravel-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Semantic Version
        id: semver
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE:|feat!:|fix!:"
          minor_pattern: "feat:"
          version_format: "${major}.${minor}.${patch}"
          bump_each_commit: true
          search_commit_body: true

      - name: Create and push tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a v${{ steps.semver.outputs.version }} -m "Release v${{ steps.semver.outputs.version }}"
          git push origin v${{ steps.semver.outputs.version }}

      # This code need actual AWS credentials and EKS to work, so it's commented out for now.

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
      #     aws-region: ${{ env.AWS_REGION }}

      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v2

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Extract metadata
      #   id: meta
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}
      #     tags: |
      #       type=raw,value=${{ steps.semver.outputs.version }}
      #       type=raw,value=${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}
      #       type=raw,value=${{ steps.semver.outputs.major }}
      #       type=raw,value=latest

      # - name: Build and push
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max

      # - name: Update kubeconfig
      #   run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      # - name: Set up Helm
      #   uses: azure/setup-helm@v3
      #   with:
      #     version: 'latest'

      # - name: Deploy to EKS with Helm
      #   run: |
      #     IMAGE_TAG=$(echo ${{ steps.meta.outputs.tags }} | cut -d',' -f1)
      #     helm upgrade --install laravel-app ${{ env.HELM_CHART_PATH }} \
      #       --set image.repository=$(echo $IMAGE_TAG | cut -d':' -f1) \
      #       --set image.tag=$(echo $IMAGE_TAG | cut -d':' -f2) \
      #       --wait --timeout 5m
