name: Pull Request Validation

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  php-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, zip, pdo, pdo_pgsql, bcmath, pcntl
          coverage: none
          tools: composer

      - name: Cache composer
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-8.4-${{ hashFiles('composer.lock') }}
          restore-keys: composer-8.4-

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: App env
        run: cp .env.example .env

      - name: Generate key
        run: php artisan key:generate || true

      - name: Lint (Pint)
        run: vendor/bin/pint --test

      - name: Run tests
        run: vendor/bin/phpunit --testdox

  docker-build:
    runs-on: ubuntu-latest
    needs: php-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: laravel-app:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Docker image
        run: docker image inspect laravel-app:test
